### PR TITLE
Added theme to main page

### PR DESCRIPTION
**Pull request by emkelley**

### CODE REVIEW

**Comment by diomed** [comment]
nice!
could menu be fixed or sticky, maybe?

**Comment by diomed** [comment]
p.s. word Bulma in footer is not in good color. should be brighter.

**Comment by diomed** [comment]
would you mind if I added lightbox for pictures?

**Comment by emkelley** [comment]
By all means go for it! I'm quite partial to [Fullscreen Lightbox](https://fslightbox.com/javascript) for lightboxes on static sites if you wanted a starting point

**Pull request merged**
